#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=teamspeak
db_user=teamspeak

# Generate random DES key & password
deskey=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Initialize database and store variables for future use
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting $app mysqldb -v "$db_user"
sudo yunohost app setting $app mysqlusr -v "$db_user"
sudo yunohost app setting $app mysqlpwd -v "$db_pwd"

# Initialize user with homefolder, where we store teamspeak3 files
ts3_path=/home/$db_user
sudo useradd $db_user -m

# Copy source amd64 files to ts3 path (3.0.12.3)
sudo cp -a ../source/amd64/. $ts3_path

# Configure TS3 + MySQL / MariaDB
sed -i "s@DB_USER@$db_user@g" ../config/ts3db_mariadb.ini
sed -i "s@DB_PW@$db_pwd@g" ../config/ts3db_mariadb.ini
sed -i "s@TS_USER@$db_user@g" ../config/ts3server.service
sudo cp ../config/ts3db_mariadb.ini $ts3_path/ts3db_mariadb.ini
sudo cp ../config/ts3server.service /lib/systemd/system/$app.service
sudo chown -R $db_user:$db_user $ts3_path

# Install required lib libmariadb2
cd /tmp/
sudo wget http://ftp.de.debian.org/debian/pool/main/m/mariadb-client-lgpl/libmariadb2_2.0.0-1_amd64.deb
sudo dpkg -i libmariadb2_2.0.0-1_amd64.deb
sudo rm libmariadb2_2.0.0-1_amd64.deb

# Enable and start service
sudo systemctl enable $app.service
sudo systemctl start $app.service
