#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -eu

# Set common variables
app=$YNH_APP_INSTANCE_NAME
db_user=$(sudo yunohost app setting $app mysqldb)
root_pwd=$(sudo cat /etc/yunohost/mysql)

# Disable and remove service
sudo systemctl stop $app.service
sudo systemctl disable $app.service
sudo rm /lib/systemd/system/$app.service

# Remove teamspeak user, folder and files
sudo userdel -r $db_user

# Add firewall rules
sudo yunohost firewall disallow UDP 9987
sudo yunohost firewall disallow TCP 10011
sudo yunohost firewall disallow TCP 30033

# Remove yunohost teamspeak service
sudo yunohost service remove $app

# Remove teamspeak database
mysql -u root -p$root_pwd -e "DROP DATABASE $db_user ; DROP USER $db_user@localhost ;"
