#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# The user used to execute teamspeak
db_user=teamspeak

# Initialize user with homefolder, where we store teamspeak3 files
ts3_path=/home/$db_user

# Copy updated source amd64 files (3.0.12.3) to ts3 path
sudo cp -a ../source/amd64/. $ts3_path
sudo chown -R $db_user:$db_user $ts3_path
